<header>
    <nav>
        <div class="top">
            <div class="logo"><a href="#"><img src="./images/logo.png" alt="logo"></a></div>
            <div class="navigation">
                <ul>
                    <li><a href="index.php">Home page </a></li>
                    <li><a href="jobs.php">Position Descriptions page</a></li>
                    <li><a href="apply.php">Job application page</a></li>
                    <li><a href="about.php">About us</a></li>
                    <li><a href="enhancement2.html">Enhancement 2</a></li>
                    <li><a href="Login.php">Login</a></li>
                </ul>
            </div>
        </div>

    </nav>
</header>