<nav>
        <div class="top"style ="background-color:green;color:white; width:100%" >
            <div class="navigation" >
                <ul>
                    <li style='color:;font-size:20px'><a href="manager.php">Dashboard </a></li>
                    <li style='color:;font-size:20px'><a href="enhancement.php?action=newjob">Add Job </a></li>
                    <li style='color:;font-size:20px'><a href="enhancement.php?job=joblist"> Job Listing</a></li>
                    <li style='color:;font-size:20px'><a href="enhancement.php?jobapp=jobapplications">Job Applications </a></li>
                    <li style='color:;font-size:20px'><a href="enhancement.php?jobsearch=jobsearch"> Search  Applications</a></li>
                    <li style='color:;font-size:20px'><a href="logout.php?action=logout">Logout</a></li>
                    
                </ul>
            </div>
        </div>
    </nav>